// Generated by https://quicktype.io

export interface Extras {
  coatOfArms: CoatOfArms;
  maps:       Maps;
}

export interface CoatOfArms {
  png: string;
  svg: string;
}

export interface Maps {
  googleMaps:     string;
  openStreetMaps: string;
}
