// Generated by https://quicktype.io

export interface PaisMOS {
  currencies:   Currency[];
  translations: Translations;
  flag:         string;
  name:         string;
  capital:      string;
  region:       string;
  population:   number;
}

export interface Currency {
  code:   string;
  name:   string;
  symbol: string;
}

export interface Translations {
  br: string;
  pt: string;
  nl: string;
  hr: string;
  fa: string;
  de: string;
  es: string;
  fr: string;
  ja: string;
  it: string;
  hu: string;
}
