// Generated by https://quicktype.io

export interface Countyv2List {
  name:        string;
  alpha2Code:  string;
  capital?:    string;
  population:  number;
  flag:        string;
  independent: boolean;
}
